### ISSUE TITLE
Feature: Fix common errors from OmeXml.py

### ISSUE THREAD

**Issue by Nicholas-Schaub** [tlambert03/ome-types#129]
Prior to `ome-types`, a common way to parse out OME metadata was from `OmeXml.py`. However, the data dumped from that library generally did not conform to the OME schema. Libraries such as `AICSImageIO` generally create catches to fix some of the common errors, and it might be ideal to implement something similar in `ome-types`. This could be an option in `from_xml`.

For reference:
https://github.com/AllenCellModeling/aicsimageio/blob/c49a613dc54381d11237240ba36f0ef54603a7d6/aicsimageio/metadata/utils.py#L187

**Comment by tlambert03** [comment]
a [Flag enum](https://docs.python.org/3/library/enum.html#flag) of known errors could be a good api, allowing people to contribute fixes in a selectable way:

```
from enum import Flag, auto

class XMLFixes(Flag):
    MicroManagerInstrumentDetector = auto()
    ImageIDs = auto()
    InstrumentRefs = auto()
    PixelIDs = auto()
    ChannelPlaneOrdering = auto()

    @classmethod
    def all(cls):
        import functools, operator

        return functools.reduce(operator.or_, cls)

def clean_ome_xml(xml, options: XMLFixes = XMLFixes.all()):
    ...
```

**Comment by Nicholas-Schaub** [comment]
I actually suggested this because I ran into the exact same problems they did when switching from `OmeXml.py` to `ome-types`. I think Zeiss's platform was using the same `OmeXml.py` file, and I believe that `tifffile` used it as well. I suspect that in the near term there will be quite a few complaints when trying to access older data using `OmeTiffReader`.

I do like the idea of a `Flag` to fix this.

**Comment by JacksonMaxfield** [comment]
I don't _think_ there is anything needed to further generalize the function. It's already pretty general because we knew there would be a bunch of people raising issues if it _wasn't_ general :joy:

Your list of flags is correct to what all the function does that can be generalized outside of our specific AICS failures.

All in all, feel free to copy it over and remove the last ~15 lines or so because those are AICS specific.

---

I love how much we have done to clean and maintain file usage over long periods of time because of basically three different sources (OMEXML, micromanager -- fixed upstream now, and zeiss). OMEXML itself wasn't even from us, we pulled it from Broad, we simply packaged it and made it more available :joy:.

**Comment by tlambert03** [comment]
Thanks!  One more question, without looking deeply at your function, do you have a sense for how important the order of operations is?  That is, could it be broken up into `cleaner(xml) -> xml` functions that could be run in any order?  I assume not, but it would make it easier to generalize the addition of fixes if that were possible

**Comment by JacksonMaxfield** [comment]
Great question! I personally probably wouldn't split up this section onward (which if i am assuming correctly you already somewhat planned with `ChannelPlaneOrdering`) https://github.com/AllenCellModeling/aicsimageio/blob/c49a613dc54381d11237240ba36f0ef54603a7d6/aicsimageio/metadata/utils.py#L313

But everthing else _should_ be possible to apply one at a time.

You may want to include a flag for "fix known OME namespace" because that was also an OMEXML thing. If you used OMEXML to generate OME-TIFF metadata for writing, it shoved in a non-existant OME xml schema url.

**Comment by Nicholas-Schaub** [comment]
@JacksonMaxfield I forgot, that's where I originally scraped `OmeXml.py` from...`python-bioformats` (from Broad and CellProfiler). I eventually migrated away from that because I ended up having to customize it so much...and bfio was born. I think everyone copied that.
