### ISSUE TITLE
IDs should be required, with default or default_factory

### ISSUE THREAD

**Issue by jmuhlich** [tlambert03/ome-types#30]
IDs are very much required, so `Optional` is not appropriate for the field types. Rather we want a `default_factory` that handles generating an ID when it's not given in the constructor.

**Comment by tlambert03** [comment]
It _is_ technically appropriate as far as a python dataclass & signature type is concerned... (since it is not required in the constructor anymore because we will autogenerate one). But if you want to say it's no longer `Optional`, that's going to conflict with python type.  That said, I don't think mypy will yell at you for omitting the `Optional` type, so if you just want to make that less obvious in the generated model code, that could work.  but let me know if you have something else in mind

**Comment by jmuhlich** [comment]
I agree it should be optional in the constructor signature, but `Optional` field typing is orthogonal to whether the corresponding arg to the constructor is required. `Optional` on a field indicates that _instances_ can have that attribute set to None, which is definitely not the case for our `id` fields. We only want the constructor signature to make the `id` arg optional, which is accomplished by using the `default` or `default_factory` args to `field`. If we retain the `Optional` on `id` fields, that forces any code that accesses `obj.id` to deal with the possibility that the value is `None` in order to pass type checking, even though no instance would ever actually have a None there. (I ran into this issue in the reference improvement work already)

I think I can solve this with minimal code changes by using another sentinel object like `EMPTY` as the default value for `id` fields, and gating on that value rather than `None` in `validate_id`.

**Comment by tlambert03** [comment]
> If we retain the Optional on id fields, that forces any code that accesses obj.id to deal with the possibility that the value is None in order to pass type checking, even though no instance would ever actually have a None there. 

good point, happy to have it changed
